---
on: [push, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    secrets: inherit
    with:
      archive_name: ${{ github.event.repository.name }}-firmware-${{ github.ref_name }}-${{ github.sha }}
